// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGWNuQn5e9uqvrwQcA8P4mMaqCDYUxL4',
    appId: '1:31486191012:android:fc03f8fd7a00d110284d31',
    messagingSenderId: '31486191012',
    projectId: 'yummate-8e30b',
    databaseURL: 'https://yummate-8e30b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yummate-8e30b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-WBSVfc0PQr7dfuIDQ2Cw3QqOF3bqVz4',
    appId: '1:31486191012:ios:04a71c8217673f95284d31',
    messagingSenderId: '31486191012',
    projectId: 'yummate-8e30b',
    databaseURL: 'https://yummate-8e30b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yummate-8e30b.firebasestorage.app',
    iosBundleId: 'com.example.yummate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSkrQL5nRv4zqVtHcR3-K4dfFCUiV0A0g',
    appId: '1:31486191012:web:a7764efc5ced2eb3284d31',
    messagingSenderId: '31486191012',
    projectId: 'yummate-8e30b',
    authDomain: 'yummate-8e30b.firebaseapp.com',
    databaseURL: 'https://yummate-8e30b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yummate-8e30b.firebasestorage.app',
  );

}